#!/usr/bin/python
import sys

import Adafruit_DHT

from time import sleep, strftime, time

def write_temp(temp, humi):
    with open("temp.csv", "a") as log:
        log.write("{0},{1}\n".format(strftime("%Y-%m-%d %H:%M:%S"),str(temp),str(humi)))
while True:
	humidity, temperature = Adafruit_DHT.read_retry(sensor, pin)
	write_temp(temperature, humidity)
	sleep(45)
